# fly.toml app configuration file generated for long-butterfly-9130 on 2023-08-03T15:31:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "long-butterfly-9130"
primary_region = "ams"

[env]
  PORT = "8080"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.1"

[http_service]
  internal_port = 8080
  http_checks = []
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
